"""add tipe_data to image

Revision ID: fbd03d29e73d
Revises: c02aa939b954
Create Date: 2025-06-15 11:47:45.200592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd03d29e73d'
down_revision = 'c02aa939b954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipe_data', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('tipe_data')

    # ### end Alembic commands ###
